# Generated by Django 3.2.3 on 2021-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuvote',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
