# Generated by Django 3.2.3 on 2021-06-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_winner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
