# Generated by Django 3.2.3 on 2021-06-03 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_winner_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
