# Generated by Django 3.2.3 on 2021-06-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_winner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='restaurant_id',
            field=models.IntegerField(default=0),
        ),
    ]
